### ISSUE TITLE
matchHeight not working on buttons

### ISSUE THREAD

**Issue by ChrisCapasso** [liabru/jquery-match-height#102]
I have been using matchHeight for other elements, but it is not positioning my buttons at all.  I have played with several options and gave the buttons data attributes, but alas, nothing.  The basic code is:
$(document).ready(function(){
    $(function(){
      $('.promo').matchHeight();  
    });

    $(function() {
        $('.exploreBtn').matchHeight(
            {
                byRow: true,
                property: 'bottom'
            });
    });

The url is: http://propane.dev01.1over0.com/agriculture/products-that-use-propane/flame-weed-control/

**Comment by postama** [comment]
It is my understanding that the 'property' can only have 'height' or 'min-height'. The buttons are the same height, so I don't know how matchHeight will help with that.

I can think of two different approaches to fix this.
1.) Use CSS to position the buttons at the bottom of their containers
2.) In the grey container separate it into two zones 'content' and 'button'. Then match-height on the 'content' will make the buttons sit at the same height.

**Comment by ChrisCapasso** [comment]
I had a feeling that it was beyond the realm of matchHeight!  Thanks!

**Comment by liabru** [comment]
I'd do the second option that @postama suggests. Looks like you already have got it working now? Can I close this?
