### ISSUE TITLE
Jumping anchor when calling $.fn.matchHeight._update()

### ISSUE THREAD

**Issue by ookpalm** [liabru/jquery-match-height#109]
I have a problem when calling $.fn.matchHeight._update() for updating the size for the elements on the HTML pages. Every time when $.fn.matchHeight._update() is called, the view of HTML page jumps up (y axis) to the first element's y position of the size matching element list.

For example

Element A
Element B
Element C  <-- Browser view on y axis is here, when calling $.fn.matchHeight._update()

Element A <-- Browser view on y axis jumps here.
Element B
Element C  

My elements are stacking up for viewing on mobile screen. Please suggest any solution on this issue.

**Comment by ookpalm** [comment]
Any idea?

**Comment by liabru** [comment]
I think I'll need a working example to debug this one, can you provide?

**Comment by ookpalm** [comment]
Hi liabru

I have made a video to demonstrate this issue.

[https://youtu.be/NOCyU1dHT-M](https://youtu.be/NOCyU1dHT-M)

**Comment by liabru** [comment]
Did you try enabling [maintainScroll](https://github.com/liabru/jquery-match-height#maintain-scroll-position)? I think the issue may be similar, due to browser issues when pages change size?

**Comment by ookpalm** [comment]
Thank you llabru, it works!
