### ISSUE TITLE
Vertical Align?

### ISSUE THREAD

**Issue by tuskore** [liabru/jquery-match-height#11]

**Comment by MFFoX** [comment]
@tuskore if you're still looking for vertical alignment, you can achieve  this by using the `_afterUpdate callback` like so:

    $.fn.matchHeight._afterUpdate = function (event, groups) {
        for (var key in groups) {
            var group = groups[key];
            var firstElement = group.elements.first();
            var parent = firstElement.parent('.row.equal-cols'); //or whatever your parent row selector is
            
            //where .vertical-align is whatever element(s) you're trying to vertically align
            parent.find('.vertical-align').css('line-height', firstElement.height() + 'px'); 
        }
    }

Keep in mind though, this will only work for one liners.
