### ISSUE TITLE
Auto Resize of Window

### ISSUE THREAD

**Issue by andre-lergier** [liabru/jquery-match-height#111]
If I resize the chrome-browser-window (in windows 7 and OS X 10.11.4 with "BetterSnapTool") by dragging the window to top or left or right of the monitor, matchHeight doesn't update the new heights. How can I change that?

**Comment by jonscottclark** [comment]
If the app doesn't make Chrome fire a `resize` event on the `window` object, then the matchHeight won't update, and if it doesn't, then it's a limitation of BetterSnapTool.

Try this fiddle to see if the event even gets fired and report back: https://jsfiddle.net/Lheddph4/

**Comment by liabru** [comment]
Exactly as @jonscottclark says, please check if resize gets fired. If not it's a bug with BetterSnapTool.

**Comment by phil-a** [comment]
Having this issue too. I tried the fiddle you posted and Chrome is in fact firing resize events with BetterSnapTool. However, the grid breaks when doing the same action.

**Comment by Jhollman** [comment]
Im using JQuery Mobile, the event its not triggered, and yes im having those UGLY NSFW breaks.
If cant find a solution i would have to switch to another editor, because this bug makes my app not being Responsive.
