### ISSUE TITLE
Not working with the bootstrap grid when the columns break

### ISSUE THREAD

**Issue by ludwigkaube** [liabru/jquery-match-height#113]
https://jsfiddle.net/a6pd6hmj/ 

works fine until the columns within a row are breaking

am i missing here something?

**Comment by liabru** [comment]
By default it will match heights by row, so when the columns break they are considered two rows and therefore will not have their heights matched. You should use:

    $('.eh-column').matchHeight({ byRow: false });

To disable per-row matching.

**Comment by ludwigkaube** [comment]
ah i see, thx a lot
