### ISSUE TITLE
2 line title causes matched height item to be un-even

### ISSUE THREAD

**Issue by icommstudios** [liabru/jquery-match-height#122]
**Issue:**
Any matched height item with a title long enough to wrap to 2 lines causes it to be un-even in height....  Great plugin and as always, any help is greatly appreciated.

**Example:** http://southernhardscapeproducts.com/ (Our Top Products at bottom)

**Jquery:**
jQuery(document).ready(function(){
         jQuery('.top-products .col-sm-4, .gallery-item').matchHeight();
         jQuery.fn.matchHeight._maintainScroll = true;
});

**Comment by liabru** [comment]
This issue isn't related to the plugin, it's just how `inline-block` works. You can resolve this by setting `vertical-align: middle` on your containers. Alternatively, you can use `float: left` and `display: block` on your containers instead.

**Comment by icommstudios** [comment]
Thanks so much!

On Mon, Jul 11, 2016 at 5:41 AM, Liam <notifications@github.com> wrote:

> This issue isn't related to the plugin, it's just how inline-block works.
> You can resolve this by setting vertical-align: middle on your
> containers. Alternatively, you can use float: left and display: block on
> your containers instead.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/liabru/jquery-match-height/issues/122#issuecomment-231688107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN7RAu3t9K8HxvNqNapeNHU40yHt9rgks5qUg_agaJpZM4JI-9E>
> .
>



-- 
*Be Happy*,
Travis Hedrick

704-902-8486
www.iCommStudios.com <http://www.icommstudios.com/>
info@icommstudios.com
