### ISSUE TITLE
error matchHeight() is not a function

### ISSUE THREAD

**Issue by ALWAYSAND4EVER** [liabru/jquery-match-height#127]
I'm newbie guys. I really wanna find out why do i keeping receive this error: matchHeight is not a function. Did i made some syntax mistakes

**Comment by ALWAYSAND4EVER** [comment]
here is my code snippet: 
$("#row").click(function() {
      $('.box').matchHeight();
});

**Comment by DavidBruchmann** [comment]
Probably you never included jquery-match-height or the path to the script is not right.
Try to call the script with the path you entered in your HTML-page directly in the browser.
The script has to be included above / before the code you posted.
You can check for any errors in the browser-console (in FireFox or Chrome you can open it with the key F12).

**Comment by ALWAYSAND4EVER** [comment]
i checked again and i'm sure that i included the script above the code i posted

**Comment by DavidBruchmann** [comment]
So then you should have some HTML like this:
<div id="row">
    <div class="box"> ... </div>
    <div class="box"> ... </div>
    <div class="box"> ... </div>
</div>

And when you click on the row the height of the inside-divisions shall be the same height?

**Comment by ALWAYSAND4EVER** [comment]
actually this is what i have:
<input type="radio" name="equal" id="row" value="2">
<label for="row">Equal height each row</label>

<div>
    <div class="box"> ... </div>
    <div class="box"> ... </div>
    <div class="box"> ... </div>
</div>

but i cant bind the click even to the matchHeight function. Everytime the browser gave me the error notification that matHeight() is not a function

**Comment by DavidBruchmann** [comment]
This small HTML-Script is working, so you must have made some other fault.
You've to adjust the paths to the jquery and jquery.matchHeight.

&lt;!Doctype HTML&gt;
&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;MatchHeight Test&lt;/title&gt;
		&lt;script src="jQuery/jquery-2.2.4.min.js" type="text/javascript"&gt;&lt;/script&gt;
		&lt;script src="jquery-match-height/jquery.matchHeight.js" type="text/javascript"&gt;&lt;/script&gt;
		&lt;style type="text/css"&gt;
		.box {
			float:left;
			width:33.333%;
			background:silver;
		}
		&lt;/style&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;input type="radio" name="equal" id="row" value="2" /&gt;
		&lt;label for="row"&gt;Equal height for each row&lt;/label&gt;
		&lt;div&gt;
			&lt;div class="box"&gt; Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore &lt;/div&gt;
			&lt;div class="box"&gt; Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore  &lt;/div&gt;
			&lt;div class="box"&gt; Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum Dolore Lorem Ipsum  &lt;/div&gt;
		&lt;/div&gt;
		&lt;script type="text/javascript"&gt;
			$("#row").click(function() {
				$('.box').matchHeight();
			});
		&lt;/script&gt;
	&lt;/body&gt;
&lt;/html&gt;

**Comment by liabru** [comment]
Thanks for helping here, @DavidBruchmann.
