### ISSUE TITLE
Wrong calculations in IE10

### ISSUE THREAD

**Issue by jongc** [liabru/jquery-match-height#128]
In IE10 (and maybe older versions), the height calculations are incorrect. I did a test in Chrome and received height numbers that include padding and all. However, in IE10, the number is much smaller. It looks like they only return the padding and no height.

**Comment by jongc** [comment]
After some snooping around, I found a CSS fix. Applying `height: auto !important` on the elements before match height fires seemed to do the trick.

**Comment by jongc** [comment]
The CSS fix above doesn't work for every element in IE10. I found that when I resize the window, the match height works. I had to add a function for window resizing like this:

```
// Trigger match height update on window resize
$(window).resize( function() {
    $.fn.matchHeight._update();
});
```

So I tried calling the function again when the window/document loads. No luck. I'm still digging. Any suggestions would be great.

**Comment by jongc** [comment]
I have resolved my issue once again! I had a FOUT script in place and I didn't read to the documentation part that says, "If you have a font that is loading...". I put all my match height goodies at the very end and executed them after my FOUT script. All good now.

**Comment by liabru** [comment]
Thanks for the update, glad you got it sorted (for now at least!).
