### ISSUE TITLE
Safari: inconsistent height 

### ISSUE THREAD

**Issue by 2sheds** [liabru/jquery-match-height#13]
Hi!
There's some issue with matchHeight plugin on my website in Safari (both Mac&iOS): the height calculated is too small and it varies on multiple page refreshes.
![screen shot 2014-07-02 at 16 21 27](https://cloud.githubusercontent.com/assets/16163/3455969/90d099e8-01e9-11e4-8574-696d2188472b.PNG)
## ![screen shot 2014-07-02 at 16 21 56](https://cloud.githubusercontent.com/assets/16163/3455967/90ca8148-01e9-11e4-8b4e-2ba0cb69e25c.PNG)

This is a reference look in Chrome:
![screen shot 2014-07-02 at 17 05 15](https://cloud.githubusercontent.com/assets/16163/3455968/90ce7eec-01e9-11e4-99fd-8649f61624f2.PNG)
Unfortunately I can't share URL yet since it's a local dev instance.

**Comment by maustyle** [comment]
hello, i didn't understand how to make Safari work with the script. FYI all the test pages are offline.

**Comment by m7ess5** [comment]
Adding `jQuery( document ).ready(function() {` fixed it for me.
