### ISSUE TITLE
Problem with wow.js and animated.css plugins

### ISSUE THREAD

**Issue by biklik** [liabru/jquery-match-height#146]
I am using this plugin and all is good but when column (boxes) have an animation with wow.js and animated.css only works when the page is loaded. If you are in the viewport in the moment of the load, it does not work...

Here is a video https://vid.me/6oHC
Is there any way to solve this problem?

**Comment by liabru** [comment]
I'm not familiar with those plugins but I'd suggest finding out what events (e.g. before and after animations or load events) they trigger and calling `$.fn.matchHeight._update()` in them.

**Comment by biklik** [comment]
Thanks! I solved the problem triggering with `$.fn.matchHeight._update()`.

Thank you!!
