### ISSUE TITLE
Page jumps up on reloading the elements when using ajax pagination

### ISSUE THREAD

**Issue by nulian** [liabru/jquery-match-height#18]
The page jumps up on reloading the elements when using ajax pagination.
I fixed it by saving the scroll position and reloading it on this part of the code.
Thought it might be usefull.

<pre><code>
if (byRow) {
      var scroll = $(window).scrollTop();
      // must first force an arbitrary equal height so floating elements break evenly
      $elements.css({
        'display': 'block',
        'padding-top': '0',
        'padding-bottom': '0',
        'border-top-width': '0',
        'border-bottom-width': '0',
        'height': '100px'
      });

      // get the array of rows (based on element top position)
      rows = _rows($elements);

      // revert the temporary forced style
      $elements.css({
        'display': '',
        'padding-top': '',
        'padding-bottom': '',
        'border-top-width': '',
        'border-bottom-width': '',
        'height': ''
      });
      $(window).scrollTop(scroll);
    }
</code></pre>

**Comment by fro** [comment]
@liabru `$.fn.matchHeight._maintainScroll = true;` is a brilliant feature, thank you. :-)

**Comment by ksaifullah** [comment]
@liabru Thank you very much. It saved my hours of work.
