### ISSUE TITLE
Height Property

### ISSUE THREAD

**Issue by kiballion** [liabru/jquery-match-height#30]
Hey there,

Congrats for your plugin! You might consider setting the min-height param and not the height as it will allow more flexibility; just a quick hint :)

Radu

**Comment by Akrion** [comment]
Hi, I am using the 0.5.2 version and the above fix does not seem to work. Was the min-height released as part of the 0.5.2? Thanks again for your work and for sharing.

**Comment by liabru** [comment]
This feature is currently only in the latest master build so please use that for the time being, thanks.

**Comment by Akrion** [comment]
Thanks. Will do.
