### ISSUE TITLE
Height issues with ajax

### ISSUE THREAD

**Issue by ghost** [liabru/jquery-match-height#31]
Hi,

I'm using `matchHeight()` on a WordPress site, and its working fine on initial render. But I'm using [Ajax Load More](https://wordpress.org/plugins/ajax-load-more/) to load more posts, using jQuery's `ajaxComplete()` to update the height on loaded posts. It's working fine on the first load, but on the second load the heights are set to high (should be around 300px, gets set to around 500px).

Here is my JS:

```
    jQuery.noConflict();
    jQuery(document).ready(function($){

        $(function() {
            $('#employees .person').matchHeight();
        });

        $( document ).ajaxComplete(function() {
            $.fn.matchHeight._apply('#employees .person')
            $.fn.matchHeight._maintainScroll = true;
        }); 

    });
```

And ideas?

**Comment by apmeyer** [comment]
I can confirm that the [initial recommendation above](https://github.com/liabru/jquery-match-height/issues/31#issuecomment-55142416) from @liabru works well with Ajax Load More in WordPress. Thank you for that tip!

**Comment by pierre-r** [comment]
Hello,

It is not the first time I am confronted to this issue.
If, like me, you are using the Data API, `$.fn.matchHeight._update();` doesn't seem to work for some reasons.
Instead, I am calling `$.fn.matchHeight._applyDataApi();`

Here is an exemple :
```
// statechangecomplete is the event I trigger when AJAX call has successfully ended
$(window).on('load statechangecomplete', function () {
    $.fn.matchHeight._applyDataApi();
});
```
