### ISSUE TITLE
height calculating not working properly

### ISSUE THREAD

**Issue by mjot** [liabru/jquery-match-height#40]
Hi,

at first thanks for your great plugin. :) I used it on one page without problem, but on a new layout, I'm having problems with the calculated height. I made a jsfiddle to show the problem.

The last Box is always falling out, because the height is calculated to small:

http://jsfiddle.net/emjay__/xp1g0d0f/

If I add another box to the last row, it is working again. I hope this problem is fixable. :)

Thanks

**Comment by simonswiss** [comment]
FYI i just had the exact same issue (this is how i ended up here) and i could fix it by adding <code>"vertical-align: top"</code> to my inline-block elements i wanted to match height.

No idea why, but it worked great!

Hopefully that can help you guys :)

**Comment by slackero** [comment]
Use an empty clearfix element after the last grid item. http://jsfiddle.net/xp1g0d0f/6/ Check widths of your columns. Your floating seems to be in-optimal (check width, margin and so on). Check how bootstrap & Co. solving the problems.

**Comment by liabru** [comment]
This has been resolved see #88, you should use the [latest master](https://github.com/liabru/jquery-match-height/blob/master/jquery.matchHeight.js) for now, until the next release which will include this.
