### ISSUE TITLE
Height wrong on older Firefox / jQuery versions

### ISSUE THREAD

**Issue by FreekyMage** [liabru/jquery-match-height#41]
In some companies they don't allow Firefox to automatically update. I have a client who is stuck on FF 27 because of this and the height is not calculated correctly when box-sizing is used.
See http://caniuse.com/#search=box-sizing

This can be fixed by changing:
```javascript
if ($that.css('box-sizing') !== 'border-box') {
```
into:
```javascript
if ($that.css('box-sizing') !== 'border-box' && $that.css('-moz-box-sizing') !== 'border-box') {
```

I know this is something that shouldn't really be fixed (companies need to update), but I thought I'd post it here for people with a similar problem.

**Comment by lewisnyman** [comment]
It's quite easy to upgrade the version of jQuery in Drupal using the jQuery update module

**Comment by liabru** [comment]
Yea I think that should really be the preferred fix, so closing this thanks

**Comment by mstrelan** [comment]
I have the same issue, also in Drupal 7, using [Firefox ESR]([https://www.mozilla.org/en-US/firefox/organizations/), which is equivalent to FF24. Updating to JQuery 1.8 solved this for me.

**Comment by liabru** [comment]
@mstrelan thanks for the confirmation. Upgrading is what I recommend here as I do not plan to support very old versions of jQuery.
