### ISSUE TITLE
Auto height after window resize

### ISSUE THREAD

**Issue by djmtype** [liabru/jquery-match-height#44]
On load, this plugin works great, but when I filter using [mixitup plugin](https://mixitup.kunkalabs.com/), things start to break. I assume I need a callback function to re-evaluate the height. The following doesn't work. Otherwise, if this question is for the MixItUp dev, then sorry for the trouble.

```
$(window).resize(function() {
$.fn.matchHeight._update('.item');
});
```

```
$(function(){
$('#mixitup').mixItUp({
  animation: {
    effects: 'fade scale',
    animateResizeTargets: true
  },
  callbacks: {
    onMixEnd: function(){
    $.fn.matchHeight._update('.item');
    }
  }
});
});
```

**Comment by liabru** [comment]
I'm going to assume you sorted this and close, but feel free to update if not.
