### ISSUE TITLE
Stacked Group Items Potential Issue Fix

### ISSUE THREAD

**Issue by sjbeatle** [liabru/jquery-match-height#48]
First, fantastic plugin! Kudos!

Something I noticed was that when reducing the screen width to the point where all items in a group were stacked on top of each other (essentially single item rows), the height would continue to be set to whatever the last value was prior to being stacked.

I believe the issue can be fixed by changing the code on lines 201-203 from this:
  // skip apply to rows with only one item
  if (opts.byRow && $row.length <= 1)
    return;

To something more like this (I'm sure you'll know a better way to implement this, pardon my crude coding):
  // set item height to auto for rows with only one item
  if (opts.byRow && $row.length <= 1) {
    $(this).css('height','auto');
    return;
  }

Thanks again, maybe this enhancement can make an already amazing plugin just a teeny bit better.

~Steve

**Comment by liabru** [comment]
Well spotted, thank you for reporting this!

**Comment by sjbeatle** [comment]
Sweet! My pleasure.
