### ISSUE TITLE
New Release Candidate

### ISSUE THREAD

**Issue by MFFoX** [liabru/jquery-match-height#49]
Can we get a new release? I am currently using this via bower (v0.5.2) and I really need access to the callback functions.

There are quite a few bug fixes and features that would be nice to have as well as the callbacks :)

**Comment by liabru** [comment]
Doesn't bower pull through the latest master version from the repo? I just tried it and it seems to?
(if so you already should have the latest features, despite the old version number!)

Though, I realise this is misleading so I should provide a new release asap :)

**Comment by MFFoX** [comment]
I am not experiencing that. When I install using the package's registered name e.g.

    $ bower install matchHeight

I get the following:

    bower matchHeight#*             cached git://github.com/liabru/jquery-match-height.git#0.5.2
    bower matchHeight#*           validate 0.5.2 against git://github.com/liabru/jquery-match-height.git#*
    bower matchHeight#~0.5.2       install matchHeight#0.5.2

I am currently forcing the latest commit from master by using the repo's endpoint and specifying the SHA e.g.

    $ bower install https://github.com/liabru/jquery-match-height.git#64b9a547f4

which will make you specify that you want this commit instead of the version 0.5.2:

    bower matchHeight#~0.5.2        cached git://github.com/liabru/jquery-match-height.git#0.5.2
    bower matchHeight#~0.5.2      validate 0.5.2 against git://github.com/liabru/jquery-match-height.git#~0.5.2
    bower jquery-match-height#64b9a547f4           cached https://github.com/liabru/jquery-match-        height.git#64b9a547f4
    bower jquery-match-height#64b9a547f4         validate 64b9a547f4 against     https://github.com/liabru/jquery-match-height.git#64b9a547f4
    bower jquery-match-height#64b9a547f4        short-sha Consider using longer commit SHA to avoid conflicts

    Unable to find a suitable version for matchHeight, please choose one:
        1) matchHeight#64b9a547f4 which resolved to 64b9a547f4
        2) matchHeight#~0.5.2 which resolved to 0.5.2 and is required by test npmPrefix the choice with ! to persist it to bower.json

    ? Answer:: 1
    bower matchHeight#64b9a547f4                  install matchHeight#64b9a547f4

    matchHeight#64b9a547f4 bower_components\matchHeight

**Comment by JulienMelissas** [comment]
Yes, it would be nice to be able to have a tag/release for the recent commits, even if it's 0.5.3 or something along those lines. I'm using this in bower to get around it...
```
"dependencies": {
  ...
  "matchHeight": "master",
  ...
}
```

**Comment by thecancerus** [comment]
@liabru please do tag a new release for the lib, so that it can be pushed to cdnjs.

**Comment by liabru** [comment]
Sorry this has taken so long guys.

Here is v0.6.0:
https://github.com/liabru/jquery-match-height/releases/tag/0.6.0

Let me know if you have any issues with it!
