### ISSUE TITLE
Setting top, bottom padding to 0

### ISSUE THREAD

**Issue by Jursdotme** [liabru/jquery-match-height#51]
This part allways sets the top and buttom padding on elements to 0. Commenting the lines out them out fixes this. Am i doing something wrong?

```javascript
// get rows if using byRow, otherwise assume one row
        if (byRow) {

            // must first force an arbitrary equal height so floating elements break evenly
            $elements.css({
                'display': 'block',
                //'padding-top': '0',
                //'padding-bottom': '0',
                'border-top': '0',
                'border-bottom': '0',
                'height': '100px'
            });

            // get the array of rows (based on element top position)
            rows = _rows($elements);

            // revert the temporary forced style
            $elements.css({
                'display': '',
                //'padding-top': '',
                //'padding-bottom': '',
                'border-top': '',
                'border-bottom': '',
                'height': ''
            });
        }
```

**Comment by postama** [comment]
Are you originally setting the top and bottom padding with CSS or jQuery? If you are using CSS the second section of code will reset it to the CSS value, and shouldn't change it to 0.

**Comment by liabru** [comment]
This looks like an issue with an older version, can you try with the latest [edge build](https://github.com/liabru/jquery-match-height/blob/master/jquery.matchHeight.js)?

**Comment by Jursdotme** [comment]
Sorry. I just installed the latest release via Bower, but now i see that it was released 10 months ago. Installing the newest master fixes the problem.

I recommend you draft a new release :-)
