### ISSUE TITLE
Viewport jumping during page resize

### ISSUE THREAD

**Issue by JayCarney** [liabru/jquery-match-height#52]
Resizing the window causes the viewport to jump up the page.

I assume this is a side effect of the way the heights are calculated, and I'm not sure if there is a way around this, just thought I'd let you know.

**Comment by liabru** [comment]
Does enabling the setting [$.fn.matchHeight._maintainScroll](https://github.com/liabru/jquery-match-height#maintain-scroll-position) help with your case?

**Comment by JayCarney** [comment]
Ah, that solves it.
Sorry I didn't notice that in the readme
