### ISSUE TITLE
Pass data-mh to line-height

### ISSUE THREAD

**Issue by Seppentoni** [liabru/jquery-match-height#53]
Hi.

Is it possible to pass the calculated height to other style attributes like line height?
(This way it would be peace of cake to vertically align text).

**Comment by liabru** [comment]
You could probably do it using the callback event:

    $.fn.matchHeight._afterUpdate = function(event, groups) {
        // do something after all updates are applied
    }

You could loop through the elements that you need to apply this to, set their `line-height` to their `height` value?

**Comment by Seppentoni** [comment]
I found another solution: http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

Together with matchHeight.js this works great.

**Comment by liabru** [comment]
Hey awesome, I'll close this one then thanks.
