### ISSUE TITLE
Hidden content is not calculated

### ISSUE THREAD

**Issue by mahanteshpatil67** [liabru/jquery-match-height#55]
Hi
First of all, thanks for such an awesome plugin, it works like a charm, I have used it in my project mentioned below and it works perfectly as expected.

However, I have a unique issue, in my project there is a hidden content, and on click of a button (button name is hidden content) we are showing the content inside the div, but when I click on the button only that div is expanding, not the other 2 div, also the parent div classes are not applying due to fixing the height at the initial level.

Below is the link.

http://pacificit.in/visitfree1/overview.html

Kindly check the below image to have a look at initial stage

![initial](https://cloud.githubusercontent.com/assets/10774618/6424567/1432cbec-bf24-11e4-9ee3-3a8687acdb55.png)

Below is the image after I click on the hidden content button

![error](https://cloud.githubusercontent.com/assets/10774618/6424568/28ac9fe4-bf24-11e4-921d-6d2bd5edb3bf.png)

**Comment by livin52** [comment]
This is common behaviour for any browser. Something that is "display:none" has no height nor width, therefore is not calculated. You could call the matchHeight again when you display new content to force the recalculation of the containers height.

**Comment by mahanteshpatil67** [comment]
Thanks for the input, it worked.

**Comment by liabru** [comment]
@livin52 is correct (although there is support for matching heights of elements that are inside hidden parents, but it may not always be reliable)

Generally dynamic content requires manual updates, [see here](https://github.com/liabru/jquery-match-height#content-changes-require-a-manual-update).
