### ISSUE TITLE
Can we vertically align the elements?

### ISSUE THREAD

**Issue by niranjans** [liabru/jquery-match-height#61]
I have tried a few different solutions like `vertical-align: middle;` and some others but can't seem to figure this out. 

The height matching is working for me but is it possible to align the inner elements to center align vertically inside the divs?

**Comment by liabru** [comment]
I don't expect there'd be an issue when using matchHeight and the usual techniques for vertical align in CSS.

See #53 for a discussion where a user reported success with a particular technique that you may want to try.

**Comment by niranjans** [comment]
Ahh yes, I tried to look through all the issues before posting but I guess I missed that one, Thanks!
