### ISSUE TITLE
TypeError: Cannot read property 'target' of undefined 

### ISSUE THREAD

**Issue by Akrion** [liabru/jquery-match-height#63]
After your latest update the call to 
```javascript
$(element).find(args).matchHeight();
```
fails with "TypeError: Cannot read property 'target' of undefined "

The workaround was to call with an empty object like this:
```javascript
$(element).find(args).matchHeight({});
```
Bug is in your check for target (line 114)
```javascript
if (this.length <= 1 && !options.target) {
   return this;
}
```
Also anyway you can tag your releases so we do not blindly use master (I need the min-height feature)?

As always thanks you for your work and for sharing this.

**Comment by liabru** [comment]
Apologies. I'll get a new release arranged!
