### ISSUE TITLE
Placeholder rule until page loads?

### ISSUE THREAD

**Issue by mokanfar** [liabru/jquery-match-height#66]
Hi I am using this fabulous script on my responsive product grid items for my e-commerce website. I noticed upon page load of a category with around 30 products, the height of the container that I am height matching is initially compacted, because the product images do not load completely, which looks unpleasing to the eye. Upon page load the script works fine no issues. 

I was wondering if there was a work around to make the container a bigger fixed size maybe like a little CSS face-lift rule so it doesnt look TOO compact? And if I am dealing with responsive site how to keep that in mind with varying container size (media queries perhaps?)

**Comment by liabru** [comment]
This is a common problem but it's really out of the scope of this plugin.

I think something like this [placeholder example](http://maketea.co.uk/2013/05/04/responsive-image-placeholders.html) should help you solve this?

**Comment by mokanfar** [comment]
That works perfectly, and caters to responsive design! Thank you!
