### ISSUE TITLE
Is it possible to match the height according to its width or vice versa?

### ISSUE THREAD

**Issue by mayeenulislam** [liabru/jquery-match-height#67]
Is it possible to match the height according to its width or vice versa - so that I can serve a square element?

**Comment by liabru** [comment]
If you just need to maintain an aspect ratio there are some techniques for this like [this one](http://www.mademyday.de/css-height-equals-width-with-pure-css.html), is that what you were thinking of?

**Comment by liabru** [comment]
This would be neat but would be tricky to implement due to all of the special cases, so I'd prefer if you used one of the above techniques, so closing this, thanks.
