### ISSUE TITLE
Oldest version of jQuery library that is supported

### ISSUE THREAD

**Issue by homeruntaz** [liabru/jquery-match-height#71]
Dealing with a corporate website - they're using 1.8.14 which doesn't seem to work. It'll be difficult to get them to upgrade to the latest because of all the other jQuery plugins they're using. I tried 1.11 locally and it works great but wondering if there's something that can be done for a legacy library version.

**Comment by liabru** [comment]
Seems to work fine for me with 1.8.3 and even back to 1.6.4.
See this fiddle: https://jsfiddle.net/liabru/cqnvgvxd/

Can you provide more information or a fiddle on the issue you're seeing?

**Comment by liabru** [comment]
I'm going to close this and assume you got it working, otherwise please respond with more info. Thanks.
