### ISSUE TITLE
Not working on DIVs with inline-block display and floated (left or right)

### ISSUE THREAD

**Issue by fccdesign** [liabru/jquery-match-height#72]
This plugin works absolutely awesome, but I just found that it doesn't work with elements displayed as "inline-block" and floated (left or right), which in my case, it was intended to center 3 divs inside another div. If the "childs" are floated, it works, otherwise, it doesn't.

Any chance to use matchHeight in divs that are not floated and displayed as "inline-block"?

**Comment by liabru** [comment]
Can you provide a jsfiddle of your use case? I can't think of a good example where I'd use inline-block and floats at the same time so it's hard to reproduce the issue.

**Comment by ArmorDarks** [comment]
When you're using float on your `inline-block` element, it becomes `blocks`.

That's probably root of your issue. You can't have floated inline-blocks.

https://developer.mozilla.org/en-US/docs/Web/CSS/float

**Comment by fccdesign** [comment]
Problem Solved, Thanks.
