### ISSUE TITLE
Wrap in npm package?

### ISSUE THREAD

**Issue by maksimf** [liabru/jquery-match-height#73]
Can you please wrap library into npm package and publish it as well?

**Comment by scottdejonge** [comment]
+ 1

**Comment by thomasflad** [comment]
+1

**Comment by ArmorDarks** [comment]
+1

**Comment by liabru** [comment]
Should now exist here https://www.npmjs.com/package/jquery-match-height tell me if it works for you guys!

**Comment by maksimf** [comment]
Nice, thank you!
