### ISSUE TITLE
Display: flex not working

### ISSUE THREAD

**Issue by lllopo** [liabru/jquery-match-height#77]
There was an issue with display: inline-* that I see fixed, but pretty much the same goes for display: flex. It gets replaced with display: block and this leads to wrong height. 
Both lines :
if (display !== 'inline-block' && display !== 'inline-flex')
should become 
if (display !== 'inline-block' && display !== 'flex' && display !== 'inline-flex')

**Comment by liabru** [comment]
Can you provide an example case like in #68 so I can add it to the test page? Thanks.
