### ISSUE TITLE
Class matchHeight not working, targetted matchHeight fine?

### ISSUE THREAD

**Issue by dom1080** [liabru/jquery-match-height#79]
Apologies if this is me here, I've looked through all the issues/documentation and have copied and pasted the script but cannot get it to run properly. So the matchheight function runs fine when targeting elements unilaterally i.e. 

$(function() {
    $('#block2').matchHeight({
        target: $('#block1')
    });
});

but not when matching to the largest element in its class i.e.

$(function() {
    $('.equal').matchHeight();
});

which is what I need for the responsive webpage that I'm implementing it on.. Again apologies if I'm missing something obvious here, but I've been playing with this for hours and it's defeated me for the night. Appreciate any help. Thanks

https://jsfiddle.net/1vm1gvj2/3/

**Comment by postama** [comment]
matchHeight by default only matches a row.

This will fix it

$(function() {
$('.equal').matchHeight({byRow:false});
});

I also updated the fiddle

https://jsfiddle.net/1vm1gvj2/5/

**Comment by dom1080** [comment]
Hero! Working like a charm now over here. Great plugin, thanks for matchHeight and thanks for the help! Have a good one.

**Comment by liabru** [comment]
Thanks @postama for the response.

Perhaps I should make this a bit clearer in the readme, so thanks for raising this.

**Comment by dom1080** [comment]
@postama I appear to have got you mistaken for @liabru , so thank you for your help and Liabru thank you for matchHeight! It was obvious once It'd been pointed out but I wouldn't be surprised I wasn't the last one to miss it, glad if my query can be of some help.

Cheers

**Comment by phillq** [comment]
OMG @postama, you saved me.
