### ISSUE TITLE
Not avaialble via Bower

### ISSUE THREAD

**Issue by outsmart** [liabru/jquery-match-height#83]
I have installed previously via Bower but currently I receive this error message when trying to install

bower ENOTFOUND     Package jquery-match-height not found

**Comment by madebyelmcity** [comment]
Same here. :/

**Comment by anthonysimone** [comment]
Just ran into this today as well, same error.

**Comment by liabru** [comment]
Sorry guys looks like I messed up the bower instructions last time I changed the readme.
The correct bower name is `matchheight`, like so:

    bower install matchheight
