### ISSUE TITLE
Some floating content inside one of the selected elements breaks equal height of subsequent ones

### ISSUE THREAD

**Issue by jovilog** [liabru/jquery-match-height#88]
Hi there,

first of all, this is by far the best equal heights plugin out there. So thank you.

However, I've found this case (simplified in the jsfiddle) where it fails:
http://jsfiddle.net/qoaa7d96/1/

I broke this down to the floating `figure` in the first box being the cause. Switch off `float: left` for the `figure` and everything works as expected.

Thanks for looking into it.

Regards
Danilo

**Comment by jovilog** [comment]
Anyone please?

**Comment by jorrit** [comment]
I have the same problem. One extra line made it work, namely adding `overflow: hidden` to the set of CSS rules that are used to determine rows.

See my fiddle at https://jsfiddle.net/xk8du4zp/1/. The line is at line 193.

**Comment by jovilog** [comment]
Yes, but something like a `box-shadow` gets clipped with `overflow: hidden`. The clearing method I use in my fiddle is surely among best practices for clearing floats. So I still think, this is a problem with the plugin, not the CSS, isn't it?

**Comment by jorrit** [comment]
What do you mean with this? The overflow: hidden is only applied when matchHeight changes the heights to 100px so measure the rows. Afterwards, it should be removed.

**Comment by jovilog** [comment]
Ah, I didn't look at your fiddle. I thought you mean adding `overflow: hidden;` to clear the floats to my CSS (not the plugin), which would've worked, too, but in my real code I have a `box-shadow` on the `.box` that gets clipped with `overflow: hidden;`.

So, yeah, your suggestions seems worth a pull request?

**Comment by jorrit** [comment]
It took me a while to make a good test case to go with the pull request.

**Comment by liabru** [comment]
Looks good guys, I'm super busy right now but I'll try it out and merge soon. 
Thanks for tracking down the solution @jorrit!

**Comment by jorrit** [comment]
Thanks for letting us know!

**Comment by jovilog** [comment]
Awesome. Thanks a lot @jorrit and @liabru.
