### ISSUE TITLE
Add class to first and last item in row

### ISSUE THREAD

**Issue by generatepress** [liabru/jquery-match-height#90]
Love this plugin - thanks so much for creating it.

Is it possible to tap into the code and add a class to the first and last element in each row? Would much rather use the power of this plugin to do so than write something new.

Thanks again!

**Comment by jorrit** [comment]
Wild idea: spin off row detection into a separate jQuery plugin.

**Comment by liabru** [comment]
Actually I recently exposed the `_rows` function for unit testing purposes.

If you copy the [latest master](https://github.com/liabru/jquery-match-height/blob/master/jquery.matchHeight.js), you can now just use it like this:

    var rows = $.fn.matchHeight._rows($('.item'));

    $.each(rows, function(i, row) {
        console.log(row);
        row.first().addClass('first');
        row.last().addClass('last');
    });

Here is an example:
https://jsfiddle.net/liabru/6qpr1n02/

@jorrit I thought about doing that previously actually... Now I guess you don't have to!

**Comment by generatepress** [comment]
** slow clap **

Works perfectly!
