### ISSUE TITLE
Can drop display:none

### ISSUE THREAD

**Issue by AlexHaaniWink** [liabru/jquery-match-height#95]
We're combining this with http://isotope.metafizzy.co/ . Though that probably does not specifically matter.
In some situations, for some elements a set 'display: none' is dropped. Strangely not for all hidden elements.

I haven't gone through all the code so I don't see why it would sometimes not drop display:none.
But https://github.com/liabru/jquery-match-height/blob/master/jquery.matchHeight.js#L253 does not seem handy. I think it would be better if on line 235 you store the original display value in a variable and apply that on line 253 again.

**Comment by liabru** [comment]
Is `display: none` set on the `style` attribute rather than via CSS (or set via JS)?
Looks like that would indeed fail. I'll look into getting this fixed.

**Comment by AlexHaaniWink** [comment]
It is set via the style attribute yes. Isotope uses that to filter out elements.

**Comment by liabru** [comment]
Thanks, should be resolved in the latest master.
