### ISSUE TITLE
Need to delete groups and recreate groups

### ISSUE THREAD

**Issue by shamanth7077** [liabru/jquery-match-height#98]
Hi,

I am using a jQuery plugin to filter items http://isotope.metafizzy.co/.

Initially, there are three rows ( each row having four containers), and each container has an image(img), heading(h3) and description(p).
So i am using data-mh for image, heading and description seperately and intitally byRow is true(want byRow as true as each row should be independent) so data-mh works only for highest height in that row. As I apply filter, any container can move to other rows which causes improper height, Is there a way to delete and recreate groups manually every time i filter?

I tried deleting and creating everytime on click of filter, it dint work 

```javascript
//removing match height
$('[data-mh="productlisting-p"]').matchHeight({ remove: true });
$('[data-mh="productlisting-h3"]').matchHeight({ remove: true });
$('[data-mh="productlisting-img"]').matchHeight({ remove: true });

//calling matchheight
$('[data-mh="productlisting-p"]').matchHeight();
$('[data-mh="productlisting-h3"]').matchHeight();
$('[data-mh="productlisting-img"]').matchHeight();
```

Also tried update, as groups already stored its not working.
```javascript
 $.fn.matchHeight._update();
```

<img width="243" alt="container" src="https://cloud.githubusercontent.com/assets/5626816/11955742/71f255c2-a8da-11e5-9737-791d8939d6e0.png">

Thank you,
Shamanth

**Comment by DiglidiDudeNG** [comment]
So how did you manage to solve this conundrum? I'm in the same situation right now and I have a hard time to make this lib work with the `template-extension` package version used by this lib.
